todopro/todoproject/todoapp/urls.py
from django.urls import path
from.import views
app_name='todoapp'
urlpatterns = [
      path('',views.add,name="add"),
      # path('details/',views.detail,name="details")
      path('delete/<int:taskid>/',views.delete,name="delete"),
      path('upate/<int:id>/',views.update,name="update"),
      path('cbvhome/',views.TaskListView.as_view(),name='cbvhome'),
      # path('cbvdetail/<int:pk>/',views.TaskDetailview.as_view(),name='cbvdetail'),
      path('cbvupdate/<int:pk>/',views.TaskUpdateView.as_view(),name='cbvupdate'),
      path('cbvdelete/<int:pk>/',views.TaskDeleteView.as_view(),name='cbvdelete'),
]

todopro/todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("todoapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todopro/todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()
    def __str__(self):
        return self.name

todopro/todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from.models import Task
from.form import TodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView


class TaskListView(ListView):
    model=Task
    template_name='home.html'
    context_object_name='task11'

# class TaskDetailview(DetailView) :
#     model=Task
#     template_name = 'detail.html'
#     context_object_name = 'task'

class TaskUpdateView(UpdateView):
    model=Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields=('name','priority','date')

    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetail',kwargs={'pk':self.object.id})

class TaskDeleteView(DeleteView):
    model=Task
    template_name='delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')

# Create your views here.
def add(request):
    task1 = Task.objects.all().order_by('priority').values()

    if request.method=='POST':
        name=request.POST.get('task')
        priority=request.POST.get('priority')
        date=request.POST.get('date')
        task=Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'task11':task1})

# def detail(request):
#     task=Task.objects.all()
#     return render(request,'detail.html',{'task':task})
def delete(request,taskid):
    task=Task.objects.get(id=taskid)
    if request.method=="POST":
       task.delete()
       return redirect('/')
    return render (request,'delete.html')

def update(request,id):
    task=Task.objects.get(id=id)
    f=TodoForm(request.POST or None,instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request,'edit.html',{'f':f,'task':task})

todopro/todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}

{% endblock %}
</body>
</html>

todopro/todoproject/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
    <p>Are u sure this task is done?</p>
    <button type="submit">confirm</button>

</form>
</body>
</html>

todopro/todoproject/templates/detail.html
{% extends 'base.html' %}
{% block content %}

        <div class="shadow card">

        <div class="card-body">
            <h5 class="card-title">{{task.name}}</h5>
            <p><b>{{task.priority}}</b></p>
            <p><b>{{task.date}}</b></p>
            <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
            <a class="btn btn-danger" href="{% url 'todoapp:update' task.id %}">update</a>
        </div>
    </div><br>

{% endblock %}

todopro/todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    {{f.as_p}}
    <button type="submit"> confirm</button>

</form>




{% endblock %}

todopro/todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid" align="center" >
    <div class="row" >
        <div class="col-md-14">
            <div class="banner" style="width:2020px;margin-top:5px;">
                <h1 align="center" style="padding-top:12px"> TODO   </h1>
                <div class="banner-text" >
<!--                    <h1> TODO   </h1>-->

                </div>
            </div>
        </div>
    </div>

</div>

<div class="container">
    <div class="row">
        <div class="col-md-4">
        <form method="POST" class="mb-3 shadow">
    {% csrf_token %}
       <div class="form-group">
     <input type="text"  class="form-control" name="task" placeholder="Taskname" required>
    </div>
    <div class="form-group">
      <input type="text"  class="form-control" name="priority" placeholder="Enter your priority" required>
    </div>
    <div class="form-group">
      <input type="date"  class="form-control" name="date" placeholder="Enter your Date" required>
    </div>
    <input type="submit" class="btn btn-success">

</form>

        </div>

    <div class="col-md-6">
        <h1>Task Manager</h1>
        {% for i in task11 %}
        <div class="shadow card">

        <div class="card-body">
            <h5 class="card-title">{{i.name}}</h5>
            <p><b>{{i.priority}}</b></p>
            <p><b>{{i.date}}</b></p>
            <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
            <a class="btn btn-danger" href="{% url 'todoapp:update' i.id %}">update</a>
        </div>
    </div><br>
        {% endfor %}
  </div>
</div>
    </div>


{% endblock %}

todopro/todoproject/templates/update.html
{% extends 'base.html' %}
{% block content %}

<div class="card">
  <div class="card-header">
    <div class="card-title">
      Task update
    </div>
      <div class="card-body">



<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit"> confirm</button>

</form>
   </div>
  </div>

</div>




{% endblock %}